name: Build and Push Docker Image

on:
    workflow_dispatch:
    push:
        tags:
            - "*"

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.AUTH_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: ghcr.io/${{ github.repository }}
                  tags: |
                      type=ref,event=tag
                      type=raw,value=latest

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

            - name: Change package visibility to public
              run: |
                  REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
                  response=$(curl -X PATCH \
                    -H "Accept: application/vnd.github.v3+json" \
                    -H "Authorization: token ${{ secrets.AUTH_TOKEN }}" \
                    "https://api.github.com/user/packages/container/${REPO_NAME}/visibility" \
                    -d '{"visibility":"public"}' \
                    -w "\n%{http_code}" \
                    -s)

                  status_code=$(echo "$response" | tail -n1)
                  if [ "$status_code" -ne 200 ]; then
                    echo "Failed to change package visibility. Status code: $status_code"
                    exit 1
                  fi
